[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  included_files = ["src/data/*.json"]

[[redirects]]
  from = "/api/ibar"
  to = "/.netlify/functions/ibar"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
