import {
  BarChart3,
  BriefcaseBusiness,
  Building2,
  ChartNoAxesCombined,
  CheckSquare2,
  ClipboardCheck,
  FileSearch,
  FileStack,
  Gauge,
  Headphones,
  Home,
  ListChecks,
  MessageSquareText,
  Plane,
  Radar,
  RefreshCw,
  Scale,
  Settings,
  Shield,
  ShieldCheck,
  UserRoundCog,
  UsersRound,
} from 'lucide-react';

export const navigationCatalog = {
  executive: { label: 'Executive Overview', path: '/executive-overview', icon: Home },
  operations: { label: 'Operations Overview', path: '/operations', icon: Gauge },
  accountManager: { label: 'Account Manager Workspace', path: '/account-manager', icon: UserRoundCog },
  clients: { label: 'Clients', path: '/clients', icon: Building2 },
  tasks: { label: 'My Work / Team Work', path: '/tasks', icon: CheckSquare2 },
  renewals: { label: 'Renewals', path: '/renewals', icon: RefreshCw },
  submissions: { label: 'Submissions', path: '/submissions', icon: ClipboardCheck },
  placement: { label: 'Market Placement', path: '/market-placement', icon: Plane },
  claims: { label: 'Claims', path: '/claims', icon: Headphones },
  compliance: { label: 'Compliance & Risk', path: '/compliance-risk', icon: ShieldCheck },
  documents: { label: 'Documents', path: '/documents', icon: FileStack },
  reports: { label: 'Reports & Analytics', path: '/reports', icon: BarChart3 },
  administration: { label: 'Administration', path: '/administration', icon: Settings },
  policies: { label: 'Policies', path: '/policies', icon: Shield },
  underwriterQuestions: { label: 'Underwriter Questions', path: '/underwriter-questions', icon: MessageSquareText },
  quoteComparison: { label: 'Quote Comparison', path: '/quote-comparison', icon: Scale },
  findings: { label: 'Findings', path: '/findings', icon: FileSearch },
  improvementPlans: { label: 'Improvement Plans', path: '/improvement-plans', icon: ListChecks },
  aviationRiskIndex: { label: 'Aviation Risk Index', path: '/aviation-risk-index', icon: Radar },
};

const sharedViews = [
  '/clients',
  '/renewals',
  '/submissions',
  '/market-placement',
  '/claims',
  '/compliance',
  '/compliance-risk',
  '/documents',
  '/reports',
  '/briefing',
  '/ibar',
];

export const roleExperiences = [
  {
    id: 'owner',
    label: 'Owner / Executive',
    shortLabel: 'Owner',
    icon: BriefcaseBusiness,
    activeUserId: 'USR-001',
    homeRoute: '/executive-overview',
    description: 'Monitor brokerage health, revenue, strategic risk and executive decisions.',
    primaryQuestion: 'How is the brokerage performing, and what requires executive attention?',
    priorities: ['Revenue at risk', 'High-value clients', 'Major renewals and claims'],
    navigationItems: ['executive', 'clients', 'reports', 'renewals', 'placement', 'claims', 'compliance', 'documents'],
    secondaryNavigation: ['accountManager', 'administration'],
    emphasizedNavigation: ['executive', 'reports', 'clients'],
    defaultKpis: ['annualRevenue', 'revenuePipeline', 'revenueAtRisk', 'retention', 'majorDecisions'],
    priorityTypes: ['financial-impact', 'executive-decision', 'major-claim', 'client-retention', 'team-capacity'],
    quickActions: ['Open Executive Brief', 'Review Revenue at Risk', 'Approve Placement', 'Open Major Claim'],
    iBarSuggestions: [
      'Prepare me for my day',
      'Where is revenue at risk?',
      'Which clients need executive attention?',
      'Show major claims',
      'Prepare an executive briefing',
    ],
    notificationCategories: ['financial-impact', 'client-risk', 'executive-decision', 'major-claim', 'team-capacity'],
    briefingName: "Today's Executive Briefing",
    allowedViews: [...sharedViews, '/executive-overview', '/account-manager', '/administration'],
    sidebarInsights: ['ari', 'market'],
  },
  {
    id: 'operations',
    label: 'Operations Manager',
    shortLabel: 'Operations',
    icon: ChartNoAxesCombined,
    activeUserId: 'USR-011',
    homeRoute: '/operations',
    description: 'Monitor workflow performance, team capacity and operational bottlenecks.',
    primaryQuestion: 'Where are the operational bottlenecks, and which teams need support?',
    priorities: ['Overdue work', 'Team workload', 'Delayed workflows'],
    navigationItems: ['operations', 'tasks', 'renewals', 'submissions', 'placement', 'claims', 'compliance', 'documents', 'clients'],
    secondaryNavigation: ['reports', 'administration'],
    emphasizedNavigation: ['operations', 'tasks'],
    defaultKpis: ['openWork', 'overdueTasks', 'blockedWorkflows', 'teamUtilization'],
    priorityTypes: ['overdue-work', 'capacity', 'workflow-blocker', 'handoff-delay'],
    quickActions: ['Review Bottlenecks', 'Reassign Work', 'Review Overdue Tasks', 'Open Team Workload'],
    iBarSuggestions: [
      'Where are the workflow bottlenecks?',
      'Which teams are overloaded?',
      'Show overdue operational work',
      'Which renewals are delayed?',
      'Prepare an operations briefing',
    ],
    notificationCategories: ['overdue-work', 'workflow-delay', 'capacity', 'handoff'],
    briefingName: "Today's Operations Briefing",
    allowedViews: [...sharedViews, '/operations', '/tasks', '/administration'],
    sidebarInsights: [],
  },
  {
    id: 'account-manager',
    label: 'Account Manager',
    shortLabel: 'Account Manager',
    icon: UsersRound,
    activeUserId: 'USR-002',
    homeRoute: '/account-manager',
    description: 'Manage client relationships, renewals, follow-ups and outstanding information.',
    primaryQuestion: 'Which clients and tasks need my attention today?',
    priorities: ['Client follow-ups', 'Renewal readiness', 'Missing documents'],
    navigationItems: ['accountManager', 'clients', 'tasks', 'renewals', 'submissions', 'documents', 'claims'],
    navigationLabels: { clients: 'My Clients', tasks: 'My Work' },
    secondaryNavigation: ['placement', 'compliance'],
    emphasizedNavigation: ['accountManager', 'clients', 'tasks'],
    defaultKpis: ['assignedClients', 'overdueTasks', 'renewalsDue', 'documentsMissing'],
    priorityTypes: ['client-response', 'renewal-deadline', 'missing-document', 'task-overdue', 'internal-request'],
    quickActions: ['Request Document', 'Add Note', 'Create Follow-Up', 'Prepare Meeting Brief'],
    iBarSuggestions: [
      'Which clients need me today?',
      'Show my upcoming renewals',
      'Which documents are missing?',
      'Prepare my client meetings',
      'Show my overdue tasks',
    ],
    notificationCategories: ['client-response', 'renewal-deadline', 'missing-document', 'task-overdue', 'internal-request'],
    briefingName: 'My Client Service Briefing',
    allowedViews: [...sharedViews, '/account-manager', '/tasks'],
    sidebarInsights: [],
  },
  {
    id: 'placement',
    label: 'Placement Lead',
    shortLabel: 'Placement',
    icon: Plane,
    activeUserId: 'USR-003',
    homeRoute: '/market-placement',
    description: 'Manage insurer engagement, quotations, negotiations and placement decisions.',
    primaryQuestion: 'Which insurer interactions and placement decisions require attention today?',
    priorities: ['Underwriter responses', 'Quote comparisons', 'Client placement decisions'],
    navigationItems: ['placement', 'submissions', 'renewals', 'clients', 'underwriterQuestions', 'quoteComparison', 'documents'],
    navigationLabels: { placement: 'Placement Workspace' },
    secondaryNavigation: ['claims', 'compliance', 'reports'],
    emphasizedNavigation: ['placement', 'underwriterQuestions', 'quoteComparison'],
    defaultKpis: ['marketReady', 'insurerResponses', 'quotesExpiring', 'savingsOpportunity'],
    priorityTypes: ['quote-received', 'underwriter-question', 'quote-expiry', 'client-decision', 'submission-ready'],
    quickActions: ['Record Quote', 'Respond to Underwriter', 'Compare Terms', 'Prepare Recommendation'],
    iBarSuggestions: [
      'Which quotes arrived today?',
      'Show underwriter questions',
      'Which quotations expire soon?',
      'Which placements need a recommendation?',
      'Prepare a placement briefing',
    ],
    notificationCategories: ['quote-received', 'insurer-question', 'quote-expiry', 'client-decision', 'submission-ready'],
    briefingName: "Today's Placement Briefing",
    allowedViews: [...sharedViews, '/underwriter-questions', '/quote-comparison'],
    sidebarInsights: ['market'],
  },
  {
    id: 'claims',
    label: 'Claims Coordinator',
    shortLabel: 'Claims',
    icon: Headphones,
    activeUserId: 'USR-007',
    homeRoute: '/claims',
    description: 'Coordinate open claims, carrier communication and client updates.',
    primaryQuestion: 'Which claims require intervention, and who is waiting on us?',
    priorities: ['Claims requiring intervention', 'Carrier responses', 'Financial exposure'],
    navigationItems: ['claims', 'clients', 'policies', 'documents', 'tasks'],
    navigationLabels: { claims: 'Claims Operations', tasks: 'Tasks' },
    secondaryNavigation: ['renewals', 'compliance', 'reports'],
    emphasizedNavigation: ['claims', 'tasks'],
    defaultKpis: ['brokerageAction', 'carrierAction', 'highSeverity', 'outstandingExposure'],
    priorityTypes: ['carrier-response', 'reserve-change', 'claim-document', 'client-update', 'settlement'],
    quickActions: ['Add Claim Note', 'Request Carrier Update', 'Request Client Information', 'Schedule Follow-Up'],
    iBarSuggestions: [
      'Which claims require intervention?',
      'Show claims awaiting carrier response',
      'Which claims affect renewals?',
      'Show overdue reserve updates',
      'Prepare my claims briefing',
    ],
    notificationCategories: ['carrier-response', 'reserve-change', 'claim-document', 'client-update', 'settlement'],
    briefingName: "Today's Claims Briefing",
    allowedViews: [...sharedViews, '/policies', '/tasks'],
    sidebarInsights: [],
  },
  {
    id: 'compliance',
    label: 'Compliance & Risk Advisor',
    shortLabel: 'Compliance',
    icon: ShieldCheck,
    activeUserId: 'USR-008',
    homeRoute: '/compliance-risk',
    description: 'Identify client risk, manage corrective actions and improve insurability.',
    primaryQuestion: 'Which clients present elevated risk, and what should be improved next?',
    priorities: ['Open findings', 'Corrective actions', 'Renewal risk'],
    navigationItems: ['compliance', 'clients', 'findings', 'improvementPlans', 'documents', 'aviationRiskIndex'],
    navigationLabels: { clients: 'Clients Requiring Attention' },
    secondaryNavigation: ['renewals', 'submissions', 'claims', 'reports'],
    emphasizedNavigation: ['compliance', 'findings', 'improvementPlans', 'aviationRiskIndex'],
    defaultKpis: ['highRiskClients', 'overdueFindings', 'actionsDue', 'renewalsAffected'],
    priorityTypes: ['finding-overdue', 'evidence-uploaded', 'training-expiry', 'ari-change', 'renewal-risk'],
    quickActions: ['Request Evidence', 'Create Improvement Plan', 'Approve Evidence', 'Schedule Review'],
    iBarSuggestions: [
      'Which clients present the highest risk?',
      'Show overdue corrective actions',
      'Which findings affect renewals?',
      'Show ARI-impacted clients',
      'Prepare my risk advisory briefing',
    ],
    notificationCategories: ['finding-overdue', 'evidence-uploaded', 'training-expiry', 'ari-change', 'renewal-risk'],
    briefingName: "Today's Risk Advisory Briefing",
    allowedViews: [...sharedViews, '/findings', '/improvement-plans', '/aviation-risk-index'],
    sidebarInsights: ['ari'],
  },
];

export const roleExperienceById = new Map(roleExperiences.map((role) => [role.id, role]));

export function getRoleConfiguration(roleId) {
  return roleExperienceById.get(roleId) ?? null;
}

export function getRoleNavigation(roleId) {
  const role = getRoleConfiguration(roleId);
  if (!role) return [];
  return [
    ...role.navigationItems.map((key) => ({ ...navigationCatalog[key], label: role.navigationLabels?.[key] ?? navigationCatalog[key].label, key, group: 'primary' })),
    ...role.secondaryNavigation.map((key) => ({ ...navigationCatalog[key], label: role.navigationLabels?.[key] ?? navigationCatalog[key].label, key, group: 'secondary' })),
  ];
}

export function isRouteInRoleExperience(roleId, pathname) {
  const role = getRoleConfiguration(roleId);
  if (!role) return false;
  return role.allowedViews.some((route) => pathname === route || pathname.startsWith(`${route}/`));
}
