import { validateIBarResponse } from './validation.mjs';

export function buildIBarResponse({ request, route, entities, toolResults, modelResult, operatingLayer, startedAt }) {
  const durationMs = Date.now() - startedAt;
  const response = {
    requestId: request.requestId,
    status: 'ok',
    intent: route.intent,
    confidence: route.confidence,
    title: modelResult.title,
    summary: modelResult.summary,
    statusLine: {
      label: modelResult.statusLabel,
      steps: ['validated', 'classified', 'resolved entities', 'ran tools', 'composed response'],
      durationMs,
    },
    results: toolResults.results ?? [],
    insights: toolResults.insights ?? [],
    actions: toolResults.actions ?? [],
    suggestedQueries: toolResults.executiveDailyBriefing?.suggestedQueries ?? modelResult.suggestedQueries ?? [],
    warnings: toolResults.warnings ?? [],
    executiveDailyBriefing: toolResults.executiveDailyBriefing ?? null,
    greeting: toolResults.executiveDailyBriefing?.greeting,
    businessHealth: toolResults.executiveDailyBriefing?.businessHealth,
    portfolio: toolResults.executiveDailyBriefing?.portfolio,
    priorityCount: toolResults.executiveDailyBriefing?.priorityCount,
    priorities: toolResults.executiveDailyBriefing?.priorities,
    standardWork: toolResults.executiveDailyBriefing?.standardWork,
    recommendedSequence: toolResults.executiveDailyBriefing?.recommendedSequence,
    operatingLayer,
    businessAnswer: operatingLayer?.businessAnswer ?? null,
    actionCards: operatingLayer?.actionCards ?? [],
    businessImpact: operatingLayer?.businessImpact ?? null,
    recommendedActions: operatingLayer?.recommendedActions ?? [],
    supportingRecords: operatingLayer?.supportingRecords ?? [],
    relatedWorkspaces: operatingLayer?.relatedWorkspaces ?? [],
    relatedQuestions: operatingLayer?.relatedQuestions ?? [],
    reasoningSummary: operatingLayer?.reasoningSummary ?? null,
    briefing: operatingLayer?.briefing ?? null,
    workflowPlan: operatingLayer?.workflowPlan ?? null,
    smartPriorities: operatingLayer?.smartPriorities ?? null,
    commandPalette: operatingLayer?.commandPalette ?? null,
    meta: {
      model: modelResult.model,
      serverSide: true,
      requestSchemaVersion: '2026-07-ibar-v1',
      responseVersion: operatingLayer?.version ?? 'iBar-v1',
      capabilityFamily: operatingLayer?.capabilityFamily ?? route.intent,
      dataScope: toolResults.dataScope ?? [],
      appliedFilters: toolResults.appliedFilters ?? {},
      currentRoute: request.currentRoute,
      selectedRole: request.selectedRole,
      selectedUserId: request.selectedUserId,
      entityIds: {
        client: entities.client?.id ?? null,
        claim: entities.claim?.id ?? null,
        renewal: entities.renewal?.id ?? null,
        submission: entities.submission?.id ?? null,
        negotiation: entities.negotiation?.id ?? null,
      },
    },
  };

  return validateIBarResponse(response);
}
